<?xml version="1.0"?>
<!-- 
  KRSBI-B Robot - Actuator Definitions
  
  Actuators:
  - Gripper with BTS7960 driver
  - Kicker with capacitor charging system (2 relays)
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="actuators">

  <!-- ==================== GRIPPER ==================== -->
  <xacro:macro name="gripper" params="parent">
    
    <!-- Gripper base (fixed to robot) -->
    <joint name="gripper_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="gripper_base_link"/>
      <origin xyz="${gripper_x - 0.03} 0 ${gripper_z}" rpy="0 0 0"/>
    </joint>

    <link name="gripper_base_link">
      <visual>
        <geometry>
          <box size="0.04 ${gripper_width * 0.6} ${gripper_height}"/>
        </geometry>
        <material name="gripper"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.04 ${gripper_width * 0.6} ${gripper_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.15"/>
        <xacro:box_inertia m="0.15" x="0.04" y="${gripper_width * 0.6}" z="${gripper_height}"/>
      </inertial>
    </link>

    <!-- Left gripper arm (movable) -->
    <joint name="gripper_left_joint" type="prismatic">
      <parent link="gripper_base_link"/>
      <child link="gripper_left_link"/>
      <origin xyz="0.03 ${gripper_width * 0.25} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="0" upper="${gripper_width * 0.2}" effort="10" velocity="0.1"/>
      <dynamics damping="0.5" friction="0.1"/>
    </joint>

    <link name="gripper_left_link">
      <visual>
        <geometry>
          <box size="${gripper_depth} 0.015 ${gripper_height}"/>
        </geometry>
        <origin xyz="${gripper_depth/2} 0 0" rpy="0 0 0"/>
        <material name="gripper"/>
      </visual>
      <!-- Gripper pad -->
      <visual>
        <geometry>
          <box size="${gripper_depth} 0.008 ${gripper_height * 0.8}"/>
        </geometry>
        <origin xyz="${gripper_depth/2} -0.01 0" rpy="0 0 0"/>
        <material name="gripper_pad"/>
      </visual>
      <collision>
        <geometry>
          <box size="${gripper_depth} 0.02 ${gripper_height}"/>
        </geometry>
        <origin xyz="${gripper_depth/2} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <xacro:box_inertia m="0.05" x="${gripper_depth}" y="0.02" z="${gripper_height}"/>
      </inertial>
    </link>

    <!-- Right gripper arm (movable) -->
    <joint name="gripper_right_joint" type="prismatic">
      <parent link="gripper_base_link"/>
      <child link="gripper_right_link"/>
      <origin xyz="0.03 ${-gripper_width * 0.25} 0" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit lower="0" upper="${gripper_width * 0.2}" effort="10" velocity="0.1"/>
      <dynamics damping="0.5" friction="0.1"/>
      <mimic joint="gripper_left_joint" multiplier="1" offset="0"/>
    </joint>

    <link name="gripper_right_link">
      <visual>
        <geometry>
          <box size="${gripper_depth} 0.015 ${gripper_height}"/>
        </geometry>
        <origin xyz="${gripper_depth/2} 0 0" rpy="0 0 0"/>
        <material name="gripper"/>
      </visual>
      <!-- Gripper pad -->
      <visual>
        <geometry>
          <box size="${gripper_depth} 0.008 ${gripper_height * 0.8}"/>
        </geometry>
        <origin xyz="${gripper_depth/2} 0.01 0" rpy="0 0 0"/>
        <material name="gripper_pad"/>
      </visual>
      <collision>
        <geometry>
          <box size="${gripper_depth} 0.02 ${gripper_height}"/>
        </geometry>
        <origin xyz="${gripper_depth/2} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <xacro:box_inertia m="0.05" x="${gripper_depth}" y="0.02" z="${gripper_height}"/>
      </inertial>
    </link>

    <!-- Ball detection sensor (conceptual) - would be IR beam break -->
    <joint name="gripper_sensor_joint" type="fixed">
      <parent link="gripper_base_link"/>
      <child link="gripper_sensor_link"/>
      <origin xyz="${gripper_depth * 0.7} 0 0" rpy="0 0 0"/>
    </joint>

    <link name="gripper_sensor_link">
      <visual>
        <geometry>
          <cylinder radius="0.003" length="${gripper_width * 0.4}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <material name="warning"/>
      </visual>
    </link>

    <!-- Gazebo gripper -->
    <gazebo reference="gripper_left_link">
      <material>Gazebo/Grey</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
    </gazebo>
    <gazebo reference="gripper_right_link">
      <material>Gazebo/Grey</material>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
    </gazebo>

  </xacro:macro>

  <!-- ==================== KICKER ==================== -->
  <xacro:macro name="kicker" params="parent">
    
    <!-- Kicker housing/solenoid -->
    <joint name="kicker_housing_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="kicker_housing_link"/>
      <origin xyz="${kicker_x - 0.05} 0 ${kicker_z}" rpy="0 0 0"/>
    </joint>

    <link name="kicker_housing_link">
      <visual>
        <!-- Solenoid body -->
        <geometry>
          <cylinder radius="0.02" length="0.05"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <material name="sensor"/>
      </visual>
      <!-- Capacitor (visual) -->
      <visual>
        <geometry>
          <cylinder radius="0.015" length="0.04"/>
        </geometry>
        <origin xyz="-0.02 0.03 0" rpy="0 0 0"/>
        <material name="electronics"/>
      </visual>
      <collision>
        <geometry>
          <box size="0.06 0.08 0.05"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <xacro:box_inertia m="0.2" x="0.06" y="0.08" z="0.05"/>
      </inertial>
    </link>

    <!-- Kicker plate (movable - prismatic joint) -->
    <joint name="kicker_joint" type="prismatic">
      <parent link="kicker_housing_link"/>
      <child link="kicker_link"/>
      <origin xyz="0.03 0 0" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit lower="0" upper="${kicker_max_extension}" effort="100" velocity="5.0"/>
      <dynamics damping="0.1" friction="0.05"/>
    </joint>

    <link name="kicker_link">
      <visual>
        <geometry>
          <box size="${kicker_depth} ${kicker_width} ${kicker_height}"/>
        </geometry>
        <material name="kicker"/>
      </visual>
      <collision>
        <geometry>
          <box size="${kicker_depth} ${kicker_width} ${kicker_height}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <xacro:box_inertia m="0.1" x="${kicker_depth}" y="${kicker_width}" z="${kicker_height}"/>
      </inertial>
    </link>

    <!-- Gazebo kicker -->
    <gazebo reference="kicker_link">
      <material>Gazebo/Orange</material>
      <mu1>0.8</mu1>
      <mu2>0.8</mu2>
    </gazebo>

  </xacro:macro>

</robot>
